import type { Metadata } from "next";
import localFont from 'next/font/local'
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

const font = localFont({
  src: [
    {
      path: './fonts/Soehne-Bold.woff2',
      weight: '700',
    },
    {
      path: './fonts/Soehne-Regular.woff2',
      weight: '400',
    },
  ],
})

export const metadata: Metadata = {
  title: "ChatGPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} text-sm font-light antialiased`}
      >
        <main className="grid grid-cols-[1fr_5fr]">
          <Sidebar />
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
