import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const font = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "ChatGPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} text-sm font-light antialiased`}
      >
        <main className="grid grid-cols-[1fr_5fr]">
          <Sidebar />
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
